export const actions = {
  TODO_LIST_SET:"TODO_LIST_SET",
  ITEM_IS_DONE_SET:"ITEM_IS_DONE_SET",
  ITEM_ADD:"ITEM_ADD",
  ITEM_REMOVE:"ITEM_REMOVE",
  ITEM_UPSERT:"ITEM_UPSERT",
  TODO_FORM_DIALOG_SHOW:"TODO_FORM_DIALOG_SHOW",
  TODO_FORM_DIALOG_HIDE:"TODO_FORM_DIALOG_HIDE",
  TODO_FORM_TITLE_SET:"TODO_FORM_TITLE_SET",
  TODO_FORM_DESCRIPTION_SET:"TODO_FORM_DESCRIPTION_SET",
};
